spring:
  application:
    name: hotel-search
  threads:
    virtual:
      enabled: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9093}
    producer:
      acks: 1
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        "delivery.timeout.ms": 120000
        "request.timeout.ms": 30000
        "linger.ms": 5
        "enable.idempotence": false
    consumer:
      group-id: hotel-search-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  datasource:
    url: ${DB_URL:jdbc:postgresql://postgres:5432/hotelsearch}
    username: ${DB_USER:hotelsearch}
    password: ${DB_PASSWORD:hotelsearch}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      keepalive-time: 30000

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

hotel:
  search:
    kafka:
      topic: hotel_availability_searches

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui/index.html

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
